server:
  port: 9000

management:
  server:
    port: 9001
    address: 127.0.0.1
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: beans

spring:
  application:
    name: Excel to Json
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  boot:
    admin:
      client:
        url: http://localhost:8080
        username: user
        password: password