
server:
  port: 9443
  ssl:
    key-store: classpath:keystore/si.jks  #alternativ gui/src/main/resources/keystore/si.p12(.jks)
    key-store-type: jks
    key-store-password: password
    key-alias: ssl
    enabled: true

security:
  basic:
    enabled: false

management:
  server:
    port: 9001
    address: 127.0.0.1
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: beans

spring:
  application:
    name: Excel to Json
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  boot:
    admin:
      client:
        url: http://localhost:8080
        username: user
        password: password